
    import React from 'react';

    const ReportMetaFooter = ({ reportDate }) => {
      return (
        <div className="mt-10 pt-6 border-t border-slate-300 dark:border-slate-600 text-center text-xs text-slate-500 dark:text-slate-400 print:mt-4 print:pt-2">
          <p>Report generated by Zooesis&trade; on {reportDate}.</p>
          <p>This is a digitally generated report. For veterinary use only.</p>
        </div>
      );
    };

    export default ReportMetaFooter;
  